import { CreateWebpackConfig } from "./workflow/build";

export default CreateWebpackConfig({

  onEnvUpdate({ env }) {
    // Enable cache based on server
    env.cache = env.cache || !env.server
  },

  onModulesUpdate({ typescript, css, assets, env }) {
    // Enable fast build alongside with ts-checker-plugin
    typescript.build = "fast"

    // Enable modules from css-loader (Documentation here: https://github.com/webpack-contrib/css-loader#modules)
    css.modules = true
  },

  onAssetsUpdate(config) {
    const { pipeline } = config.assets

    pipeline.verbose = true

    // Typescript
    const scripts = pipeline.source.add("app/scripts")
    scripts.file.add("main.ts", {
      output: { ext: ".js" },
      cache: { ext: ".js" },
      tag: "entry:js",
    })

    // Add file to the manifest
    // Thanks to CSSExtractPlugin, main.css will be generated by main.ts
    pipeline.shadow.addFile("main.css")

    // Views
    const views = pipeline.source.add("app/views")
    views.file.ignore("**/_*.html.ejs")
    views.file.add("**/*.html.ejs", {
      output: { ext: "" }, // Remove .ejs extension
      cache: false,
      tag: "entry:html"
    })

    // CSS
    const styles = pipeline.source.add("app/styles")
    styles.file.add("**/*.css", {
      tag: "entry:css"
    })

    // Assets
    const assets = pipeline.source.add("app/assets")
    assets.file.add("**/*", {
      baseDir: "assets", // Keep assets directory
      tag: "asset"
    })

    // Register a copy
    // Not required any more thanks to file-loader and new asset_* helpers
    // if (!config.env.server) assets.fs.copy("**/*")
  },

  onWebpackUpdate({ webpack }) {
    // Enable alias from app/scripts
    webpack.resolve.modules.push('app/scripts')
  },

})