# Extend another environment file
extend: development.yml

# Enable watch mode
watch: false

# Reload page on change
reload: false

# Enable js/css compress
compress: true

# Enable cache-break
cache: true

# Build output
output: release